[libraries]
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3", version = "1.0.0" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui", version = "1.3.0" }
