[versions]
android = "7.3.1"
changelog = "1.3.1"
composeJetbrains = "1.2.0"
detekt = "1.21.0"
dokka = "1.7.20"
gradleEnterprise = "3.11.2"
gradlePublish = "1.0.0"
hubdle = "0.2.0-alpha.43"
intellij = "1.9.0"
javierscSemverGradlePlugin = "0.3.0-alpha.4"
jgit = "6.3.0.202209071007-r"
kotlin = "1.7.20"
kotlinBinaryValidator = "0.12.0"
kover = "0.6.1"
mkdocs = "2.4.0"
nexusPublish = "1.1.0"
semver = "0.1.0-beta.10"
sonarqube = "3.4.0.2513"
spotless = "6.11.0"
testLogger = "3.2.0"
tripleT = "3.7.0"

[libraries]
adarshr-gradleTestLoggerPlugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "testLogger" }
android-toolsBuild-gradle = { module = "com.android.tools.build:gradle", version.ref = "android" }
diffplug-spotless-spotlessPluginGradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
github-gradleNexus-publishPlugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexusPublish" }
github-tripletGradle-playPublisher = { module = "com.github.triplet.gradle:play-publisher", version.ref = "tripleT" }
gitlab-arturboschDetekt-detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-enterprise-comGradleEnterpriseGradlePlugin = { module = "com.gradle.enterprise:com.gradle.enterprise.gradle.plugin", version.ref = "gradleEnterprise" }
gradle-publish-pluginPublishPlugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradlePublish" }
javiersc-semver-semverCore = { module = "com.javiersc.semver:semver-core", version.ref = "semver" }
javiersc-semver-semverGradlePlugin = { module = "com.javiersc.semver:semver-gradle-plugin", version.ref = "javierscSemverGradlePlugin" }
jetbrains-compose-composeGradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeJetbrains" }
jetbrains-dokka-dokkaGradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
jetbrains-intellijPlugins-gradleChangelogPlugin = { module = "org.jetbrains.intellij.plugins:gradle-changelog-plugin", version.ref = "changelog" }
jetbrains-intellijPlugins-gradleIntellijPlugin = { module = "org.jetbrains.intellij.plugins:gradle-intellij-plugin", version.ref = "intellij" }
jetbrains-kotlin-kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
jetbrains-kotlinx-kover = { module = "org.jetbrains.kotlinx:kover", version.ref = "kover" }
jetbrains-kotlinx-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
sonarqube-scannerGradle-sonarqubeGradlePlugin = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarqube" }
vyarus-gradleMkdocsPlugin = { module = "ru.vyarus:gradle-mkdocs-plugin", version.ref = "mkdocs" }

[plugins]
javiersc-hubdle = { id = "com.javiersc.hubdle", version.ref = "hubdle" }
