name: build-changelog-renovate

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  add-updated-dependencies-to-changelog:
    if: github.actor == 'renovate[bot]'

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Set up Java
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Add updated dependencies to the CHANGELOG from Renovate
        run: ./gradlew addChangelogItem --renovateCommitTable

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff
          git add .
          git commit --amend --no-edit --author="GitHub Action <action@github.com>"
          git push --force
